"""add phone to profiles

Revision ID: 1da0e2557a11
Revises: 84e6f26b2fd5
Create Date: 2026-08-31 10:06:14.423470

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1da0e2557a11'
down_revision: Union[str, Sequence[str], None] = '84e6f26b2fd5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('profiles', sa.Column('phone', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('profiles', 'phone')
    # ### end Alembic commands ###
