"""add github link and project sync tables

Revision ID: 7c78075a9e6b
Revises: 948a36de7a61
Create Date: 2026-08-25 15:47:16.412141

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7c78075a9e6b'
down_revision: Union[str, Sequence[str], None] = '948a36de7a61'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


github_org_invite_status_enum = sa.Enum(
    'none', 'invited', 'accepted', 'expired', name='githuborginvitestatus'
)


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    github_org_invite_status_enum.create(op.get_bind())
    op.create_table('projects',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('slug', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('repo_owner', sa.String(), nullable=False),
    sa.Column('repo_name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('language', sa.String(), nullable=True),
    sa.Column('topics', sa.ARRAY(sa.String()), nullable=False),
    sa.Column('stars', sa.Integer(), nullable=False),
    sa.Column('open_issues_count', sa.Integer(), nullable=False),
    sa.Column('cached_issues', sa.JSON(), nullable=False),
    sa.Column('synced_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_projects_slug'), 'projects', ['slug'], unique=True)
    op.create_table('project_join_requests',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('contribution_areas', sa.ARRAY(sa.String()), nullable=False),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('pending', 'approved', 'rejected', name='joinrequeststatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'user_id', name='ux_project_join_requests_project_user')
    )
    op.create_index(op.f('ix_project_join_requests_project_id'), 'project_join_requests', ['project_id'], unique=False)
    op.create_index(op.f('ix_project_join_requests_user_id'), 'project_join_requests', ['user_id'], unique=False)
    op.create_table('project_members',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('joined_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'user_id', name='ux_project_members_project_user')
    )
    op.create_index(op.f('ix_project_members_project_id'), 'project_members', ['project_id'], unique=False)
    op.create_index(op.f('ix_project_members_user_id'), 'project_members', ['user_id'], unique=False)
    op.add_column('users', sa.Column('github_id', sa.BigInteger(), nullable=True))
    op.add_column('users', sa.Column('github_login', sa.String(), nullable=True))
    op.add_column('users', sa.Column('github_org_invite_status', github_org_invite_status_enum, server_default='none', nullable=False))
    op.add_column('users', sa.Column('github_org_invited_at', sa.DateTime(timezone=True), nullable=True))
    op.create_index(op.f('ix_users_github_id'), 'users', ['github_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_github_id'), table_name='users')
    op.drop_column('users', 'github_org_invited_at')
    op.drop_column('users', 'github_org_invite_status')
    op.drop_column('users', 'github_login')
    op.drop_column('users', 'github_id')
    op.drop_index(op.f('ix_project_members_user_id'), table_name='project_members')
    op.drop_index(op.f('ix_project_members_project_id'), table_name='project_members')
    op.drop_table('project_members')
    op.drop_index(op.f('ix_project_join_requests_user_id'), table_name='project_join_requests')
    op.drop_index(op.f('ix_project_join_requests_project_id'), table_name='project_join_requests')
    op.drop_table('project_join_requests')
    op.drop_index(op.f('ix_projects_slug'), table_name='projects')
    op.drop_table('projects')
    # ### end Alembic commands ###
    github_org_invite_status_enum.drop(op.get_bind())
