"""add ondelete cascade to user-owned foreign keys

Revision ID: 7f16a40fd3e6
Revises: 7c78075a9e6b
Create Date: 2026-08-25 17:27:20.244589

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7f16a40fd3e6'
down_revision: Union[str, Sequence[str], None] = '7c78075a9e6b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('audit_log', 'actor_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_constraint(op.f('audit_log_actor_id_fkey'), 'audit_log', type_='foreignkey')
    op.create_foreign_key(None, 'audit_log', 'users', ['actor_id'], ['id'], ondelete='SET NULL')
    op.drop_constraint(op.f('challenge_submissions_user_id_fkey'), 'challenge_submissions', type_='foreignkey')
    op.create_foreign_key(None, 'challenge_submissions', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('event_registrations_user_id_fkey'), 'event_registrations', type_='foreignkey')
    op.create_foreign_key(None, 'event_registrations', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('memberships_user_id_fkey'), 'memberships', type_='foreignkey')
    op.create_foreign_key(None, 'memberships', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('notifications_user_id_fkey'), 'notifications', type_='foreignkey')
    op.create_foreign_key(None, 'notifications', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('profiles_user_id_fkey'), 'profiles', type_='foreignkey')
    op.create_foreign_key(None, 'profiles', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('project_join_requests_user_id_fkey'), 'project_join_requests', type_='foreignkey')
    op.drop_constraint(op.f('project_join_requests_project_id_fkey'), 'project_join_requests', type_='foreignkey')
    op.create_foreign_key(None, 'project_join_requests', 'projects', ['project_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'project_join_requests', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('project_members_project_id_fkey'), 'project_members', type_='foreignkey')
    op.drop_constraint(op.f('project_members_user_id_fkey'), 'project_members', type_='foreignkey')
    op.create_foreign_key(None, 'project_members', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'project_members', 'projects', ['project_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'project_members', type_='foreignkey')
    op.drop_constraint(None, 'project_members', type_='foreignkey')
    op.create_foreign_key(op.f('project_members_user_id_fkey'), 'project_members', 'users', ['user_id'], ['id'])
    op.create_foreign_key(op.f('project_members_project_id_fkey'), 'project_members', 'projects', ['project_id'], ['id'])
    op.drop_constraint(None, 'project_join_requests', type_='foreignkey')
    op.drop_constraint(None, 'project_join_requests', type_='foreignkey')
    op.create_foreign_key(op.f('project_join_requests_project_id_fkey'), 'project_join_requests', 'projects', ['project_id'], ['id'])
    op.create_foreign_key(op.f('project_join_requests_user_id_fkey'), 'project_join_requests', 'users', ['user_id'], ['id'])
    op.drop_constraint(None, 'profiles', type_='foreignkey')
    op.create_foreign_key(op.f('profiles_user_id_fkey'), 'profiles', 'users', ['user_id'], ['id'])
    op.drop_constraint(None, 'notifications', type_='foreignkey')
    op.create_foreign_key(op.f('notifications_user_id_fkey'), 'notifications', 'users', ['user_id'], ['id'])
    op.drop_constraint(None, 'memberships', type_='foreignkey')
    op.create_foreign_key(op.f('memberships_user_id_fkey'), 'memberships', 'users', ['user_id'], ['id'])
    op.drop_constraint(None, 'event_registrations', type_='foreignkey')
    op.create_foreign_key(op.f('event_registrations_user_id_fkey'), 'event_registrations', 'users', ['user_id'], ['id'])
    op.drop_constraint(None, 'challenge_submissions', type_='foreignkey')
    op.create_foreign_key(op.f('challenge_submissions_user_id_fkey'), 'challenge_submissions', 'users', ['user_id'], ['id'])
    op.drop_constraint(None, 'audit_log', type_='foreignkey')
    op.create_foreign_key(op.f('audit_log_actor_id_fkey'), 'audit_log', 'users', ['actor_id'], ['id'])
    op.alter_column('audit_log', 'actor_id',
               existing_type=sa.UUID(),
               nullable=False)
    # ### end Alembic commands ###
