"""add completed_at and archived_at to projects

Revision ID: 92401ae0fce0
Revises: fa59d33b9559
Create Date: 2026-08-31 22:21:41.203640

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '92401ae0fce0'
down_revision: Union[str, Sequence[str], None] = 'fa59d33b9559'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('projects', sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('projects', 'archived_at')
    op.drop_column('projects', 'completed_at')
    # ### end Alembic commands ###
