"""add event display content fields

Revision ID: a8424df07e73
Revises: 1da0e2557a11
Create Date: 2026-08-31 13:36:59.868100

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a8424df07e73'
down_revision: Union[str, Sequence[str], None] = '1da0e2557a11'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Existing rows get placeholder defaults here (server_default so the
    # NOT NULL add succeeds against non-empty tables); scripts/seed_events.py
    # overwrites them with real content immediately after this migration runs.
    op.add_column('events', sa.Column('starts_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('events', sa.Column('venue', sa.String(), server_default='', nullable=False))
    op.add_column('events', sa.Column('description', sa.Text(), server_default='', nullable=False))
    op.add_column('events', sa.Column('what_youll_build', sa.Text(), nullable=True))
    op.add_column('events', sa.Column('schedule', sa.JSON(), server_default='[]', nullable=False))
    op.add_column('events', sa.Column('speaker_name', sa.String(), nullable=True))
    op.add_column('events', sa.Column('speaker_meta', sa.String(), nullable=True))
    op.add_column('events', sa.Column('requirements', sa.ARRAY(sa.String()), server_default='{}', nullable=False))
    op.add_column('events', sa.Column('who_should_attend', sa.Text(), nullable=True))
    op.add_column('events', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.alter_column('events', 'starts_at', server_default=None)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('events', 'created_at')
    op.drop_column('events', 'who_should_attend')
    op.drop_column('events', 'requirements')
    op.drop_column('events', 'speaker_meta')
    op.drop_column('events', 'speaker_name')
    op.drop_column('events', 'schedule')
    op.drop_column('events', 'what_youll_build')
    op.drop_column('events', 'description')
    op.drop_column('events', 'venue')
    op.drop_column('events', 'starts_at')
    # ### end Alembic commands ###
