"""add onboarding fields to profiles

Revision ID: bdaaae36d382
Revises: 3de8e7c72783
Create Date: 2026-08-25 12:20:48.312434

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bdaaae36d382'
down_revision: Union[str, Sequence[str], None] = '3de8e7c72783'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('profiles', sa.Column('first_name', sa.String(), nullable=True))
    op.add_column('profiles', sa.Column('last_name', sa.String(), nullable=True))
    op.add_column('profiles', sa.Column('registration_number', sa.String(), nullable=True))
    op.add_column('profiles', sa.Column('course', sa.String(), nullable=True))
    op.add_column('profiles', sa.Column('year_of_study', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('profiles', 'year_of_study')
    op.drop_column('profiles', 'course')
    op.drop_column('profiles', 'registration_number')
    op.drop_column('profiles', 'last_name')
    op.drop_column('profiles', 'first_name')
    # ### end Alembic commands ###
