"""add course quiz attempts and lesson completions tables

Revision ID: ddec772627d7
Revises: 0c9594141e39
Create Date: 2026-09-03 14:04:20.461225

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ddec772627d7'
down_revision: Union[str, Sequence[str], None] = '0c9594141e39'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('course_lesson_completions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('enrollment_id', sa.UUID(), nullable=False),
    sa.Column('lesson_id', sa.UUID(), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['enrollment_id'], ['course_enrollments.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['lesson_id'], ['course_lessons.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('enrollment_id', 'lesson_id', name='ux_course_lesson_completions_enrollment_lesson')
    )
    op.create_index(op.f('ix_course_lesson_completions_enrollment_id'), 'course_lesson_completions', ['enrollment_id'], unique=False)
    op.create_index(op.f('ix_course_lesson_completions_lesson_id'), 'course_lesson_completions', ['lesson_id'], unique=False)
    op.create_table('course_quiz_attempts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('enrollment_id', sa.UUID(), nullable=False),
    sa.Column('quiz_id', sa.UUID(), nullable=False),
    sa.Column('score_pct', sa.Float(), nullable=False),
    sa.Column('passed', sa.Boolean(), nullable=False),
    sa.Column('answers', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['enrollment_id'], ['course_enrollments.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['quiz_id'], ['course_quizzes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_course_quiz_attempts_enrollment_id'), 'course_quiz_attempts', ['enrollment_id'], unique=False)
    op.create_index(op.f('ix_course_quiz_attempts_quiz_id'), 'course_quiz_attempts', ['quiz_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_course_quiz_attempts_quiz_id'), table_name='course_quiz_attempts')
    op.drop_index(op.f('ix_course_quiz_attempts_enrollment_id'), table_name='course_quiz_attempts')
    op.drop_table('course_quiz_attempts')
    op.drop_index(op.f('ix_course_lesson_completions_lesson_id'), table_name='course_lesson_completions')
    op.drop_index(op.f('ix_course_lesson_completions_enrollment_id'), table_name='course_lesson_completions')
    op.drop_table('course_lesson_completions')
    # ### end Alembic commands ###
