"""add games tables (quizzes, bingo decks, sessions, players, answers)

Revision ID: eedc126ca683
Revises: b3e1d9c47a20
Create Date: 2026-09-25 06:03:27.516391

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'eedc126ca683'
down_revision: Union[str, Sequence[str], None] = 'b3e1d9c47a20'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bingo_decks',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('terms', sa.JSON(), nullable=False),
    sa.Column('created_by_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('game_quizzes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('questions', sa.JSON(), nullable=False),
    sa.Column('created_by_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('game_sessions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('kind', sa.Enum('quiz', 'bingo', name='gamekind'), nullable=False),
    sa.Column('pin', sa.String(length=6), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('status', sa.Enum('lobby', 'question', 'reveal', 'playing', 'finished', name='gamesessionstatus'), nullable=False),
    sa.Column('content', sa.JSON(), nullable=False),
    sa.Column('quiz_id', sa.UUID(), nullable=True),
    sa.Column('deck_id', sa.UUID(), nullable=True),
    sa.Column('current_index', sa.Integer(), nullable=False),
    sa.Column('question_started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('called', sa.JSON(), nullable=False),
    sa.Column('host_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['deck_id'], ['bingo_decks.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['host_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['quiz_id'], ['game_quizzes.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_game_sessions_pin'), 'game_sessions', ['pin'], unique=False)
    op.create_table('game_players',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('nickname', sa.String(length=24), nullable=False),
    sa.Column('token_hash', sa.String(), nullable=False),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('card', sa.JSON(), nullable=True),
    sa.Column('bingo_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('kicked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('joined_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['game_sessions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('session_id', 'nickname', name='ux_game_players_session_nickname'),
    sa.UniqueConstraint('token_hash')
    )
    op.create_index(op.f('ix_game_players_session_id'), 'game_players', ['session_id'], unique=False)
    op.create_table('game_answers',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('player_id', sa.UUID(), nullable=False),
    sa.Column('question_index', sa.Integer(), nullable=False),
    sa.Column('choices', sa.JSON(), nullable=False),
    sa.Column('correct', sa.Boolean(), nullable=False),
    sa.Column('points', sa.Integer(), nullable=False),
    sa.Column('answered_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['player_id'], ['game_players.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('player_id', 'question_index', name='ux_game_answers_player_question')
    )
    op.create_index(op.f('ix_game_answers_player_id'), 'game_answers', ['player_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_game_answers_player_id'), table_name='game_answers')
    op.drop_table('game_answers')
    op.drop_index(op.f('ix_game_players_session_id'), table_name='game_players')
    op.drop_table('game_players')
    op.drop_index(op.f('ix_game_sessions_pin'), table_name='game_sessions')
    op.drop_table('game_sessions')
    op.drop_table('game_quizzes')
    op.drop_table('bingo_decks')
    sa.Enum(name='gamesessionstatus').drop(op.get_bind(), checkfirst=True)
    sa.Enum(name='gamekind').drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
