"""add challenge_submissions table

Revision ID: fb56ea59bc72
Revises: fb93aaf82e3b
Create Date: 2026-08-25 13:27:11.321914

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fb56ea59bc72'
down_revision: Union[str, Sequence[str], None] = 'fb93aaf82e3b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('challenge_submissions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('challenge_slug', sa.String(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('github_url', sa.String(), nullable=False),
    sa.Column('demo_url', sa.String(), nullable=True),
    sa.Column('learned', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('challenge_slug', 'user_id', name='ux_challenge_submissions_slug_user')
    )
    op.create_index(op.f('ix_challenge_submissions_challenge_slug'), 'challenge_submissions', ['challenge_slug'], unique=False)
    op.create_index(op.f('ix_challenge_submissions_user_id'), 'challenge_submissions', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_challenge_submissions_user_id'), table_name='challenge_submissions')
    op.drop_index(op.f('ix_challenge_submissions_challenge_slug'), table_name='challenge_submissions')
    op.drop_table('challenge_submissions')
    # ### end Alembic commands ###
